### ISSUE TITLE
use custom images

### ISSUE THREAD

**Issue by comfysage** [Kenny-Hui/SplashFox#4]
hi, i love this mod but was wondering if its possible to load custom images instead of one of the default images. thnx <3

**Comment by AmberIsFrozen** [comment]
The splash screen is displayed before the Resource Pack (and it's texture) is loaded, so I have not made it a feature for now.
*That said* it should be possible to load the image from the filesystem directly, I'll see whether I can implement that :P

**Comment by AmberIsFrozen** [comment]
Added, see how do you like it :)
https://github.com/Kenny-Hui/SplashFox/actions/runs/11556894550

Place custom png under `<Your MC Directory>/config/splashfox/custom_images/`, and you should be able to see & choose them in the config GUI (located after all the built-in one) (gui isn't polished yet, I intend on separating built-in and custom ones)

**Comment by AmberIsFrozen** [comment]
I've just pushed a new 1.2.0 version which implements this, have fun~
